en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Poynings Cricket Club. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Poynings Cricket Club"
  params:
    description: "The website of Poynings Cricket Club"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
    ### calls to action ###
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "about"
      name: "About us"
      url: "/about-us/"
      weight: 2
    - identifier: "member-information"
      name: "Member Information"
      url: "/member-information/"
      weight: 3
    - identifier: "fees"
      name: "Fees"
      url: "/member-information/fees/"
      parent: "member-information"
      weight: 1
    - identifier: "docs"
      name: "Documents"
      url: "/member-information/docs/"
      parent: "member-information"
      weight: 2
    - identifier: "committee"
      name: "Management Committee"
      url: "/member-information/committee/"
      parent: "member-information"
      weight: 3
    - identifier: "ground-information"
      name: "Ground Information"
      url: "/ground/"
      weight: 4
    - identifier: "graynicolls"
      name: "Gray Nicolls PCC Club Shop"
      url: "https://www.gray-nicolls.co.uk/collections/poynings-cricket-club"
      parent: "member-information"
      weight: 9
    - identifier: "playcricket"
      name: "Play Cricket"
      url: "https://poynings.play-cricket.com"
      weight: 10